name = "rugerreactbot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "8048375769:AAFVtpdteG_gdawjdG2PX-6dbUbjSqO9t2A"
BOT_USERNAME = "Rugerreactbot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "10"
RESTRICTED_CHATS = "1234,5678"
